apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    tier: frontend
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
      tier: frontend
  template:
    metadata:
      labels:
        app: vote
        tier: frontend
    spec:
      containers:
      - image: quay.io/mkzaw/vote:v1
        name: vote
