apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  template:
    spec:
      containers:
      - name: vote
        envFrom:
          - configMapRef:
              name: vote-options
