apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: instavote
commonLabels:
  env: staging
  project: instavote
commonAnnotations:
  supported-by: sre@example.com
