apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    tier: frontend
  name: vote
spec:
  replicas: 3
  template:
    spec:
      $setElementOrder/containers:
      - name: vote
      containers:
      - image: quay.io/mkzaw/vote:v4
        name: vote
